### ISSUE TITLE
Grading question

### ISSUE THREAD

**Issue by QPEIFFE** [drachels/moodle-mod_hotquestion#104]
Moodle 4.3.5+ (Build: 20240719)

Hi there!  Apologies if this isn't really an issue.
We noticed that folks with the "teacher" role, when clicking the "View grades" button at the bottom of the activity, can only view the grade for themselves (as if they were a student) rather than being able to view all the grades of each student in the activity.  Is this intentional? 
Our expectation would be that all students would be displayed for an instructor or equivalent grading role, and we can't find a Permission that might enable or disable this.  Any ideas?

**Comment by drachels** [comment]
I would suspect you may have change the course or HotQuestion activity permissions. I just double-checked on my demo site and the teachers are able to "View grades" for everyone.

**Comment by QPEIFFE** [comment]
It was version 2024070700, and we were able to look at the capabilities included with the plugin and make a modification to our configuration that enabled the teachers to view grades for all students.  We appreciate your guidance, and apologies for making an issue tracker for this!

**Comment by drachels** [comment]
No problem, just glad you got it working the way you need it to.
