### ISSUE TITLE
Typo in lang/en/hotquestion.php file

### ISSUE THREAD

**Issue by ckong11** [drachels/moodle-mod_hotquestion#25]
Noticed that it says "studends" instead of "students" in https://github.com/drachels/moodle-mod_hotquestion/blob/master/lang/en/hotquestion.php#L68

**Comment by drachels** [comment]
Thanks for noticing that. I have changed the wording of the sentence and the change will be in the next release.

**Comment by drachels** [comment]
Had a server "burp" and inadvertently, wound up reverting to the misspelled version. The fix will be in an upcoming version.

**Comment by drachels** [comment]
Fixed.
