### ISSUE TITLE
CSV download includes all questions submitted from all courses

### ISSUE THREAD

**Issue by lfhawasli** [drachels/moodle-mod_hotquestion#26]
I have the current upgrade for MOODLE_340_STABLE. Upon testing, the CSV download, what I expected to happen was to just get a download of all the questions for the current course and activity. Instead what I am seeing is all questions ever submitted, regardless of course or activity. I tested to see if this happens in a pervious version as well and it does. I'm bringing this to your attention because I am unsure if this is the intended behavior or a bug.

Thanks,
Lillian Hawasli

**Comment by drachels** [comment]
Hi Lillian,
If my memory is correct, an admin gets every question from the whole site that has not been deleted, in a download. A teacher, gets questions for the current course activity only. Currently my development server is down for rebuild, so it will be a while before I can make sure of that.

**Comment by lfhawasli** [comment]
Just tested this, and you are correct. Thank you for clarifying.
