### ISSUE TITLE
Feature request: Hide author line in questions table

### ISSUE THREAD

**Issue by FloMiLe** [drachels/moodle-mod_hotquestion#45]
I prefer the suggested questions to be displayed without the author information line below it. Currently, I just hide that line via CSS. But I think it would be nice to have the feature to just hide the line for students.

This is different from anonymous entries in that the trainer can see the authors, but the students cannot. Plus the students have a much cleaner table, which is also easier to skim through.

**Comment by drachels** [comment]
Just got this to working, but it is quitting time for me. Need to do some more testing tomorrow, before I can release it.

**Comment by drachels** [comment]
Included as part of new Hot Question v3.9.1 release.

**Comment by drachels** [comment]
Included as part of new Hot Question v3.9.1 release.

**Comment by FloMiLe** [comment]
That is great! And thanks so much for this super useful activity!

**Comment by drachels** [comment]
You are welcome.

**Comment by FloMiLe** [comment]
I've immediately updated to the latest version and tested it. Now, the author name is hidden to the students, but visible to the teacher.

At the risk of suggesting something you might have intentionally discarded: How about hiding the whole line "Posted..."? 
I am currently doing this via CSS, see below, and really like how clean the table looks.

    #questions_list > table > tbody td.cell.c0 > div.author {
        display: none;
    }

So my suggestion would be to hide the whole line that used to show the author and posting date for students.
