### ISSUE TITLE
Your module uses the same name as the Level Up! --> Conflict in Moodle

### ISSUE THREAD

**Issue by hsworms** [drachels/moodle-mod_hotquestion#48]
Hello,

unfortunately, after the latest Moodle security update, there is a problem with your "Hot Question" module, if the "Level Up!" module is installed at the same time.

The result is an error message for the module "Level Up!
Debugging message:
Fatal error: Cannot declare class mod_data\event\comment_deleted, because the name is already in use in /var/www/moodle/moodle/mod/hotquestion/classes/event/xxxcomment_created.php on line 0

Here is the link to the discussion with the developer of the module "Level Up!", who recommended us to uninstall their module and the module "Level Up!" worked again: https://github.com/FMCorz/moodle-block_xp/issues/117.

I hope for a timely solution so that we can offer both modules in the next semester.

Thank you!

**Comment by drachels** [comment]
Look for the explanation in issue #47. There were three files accidentally included in the last Hot Question release, that should not be there and they all start with "xxx". Just delete them and you should be set.
