### ISSUE TITLE
Behat test failures

### ISSUE THREAD

**Issue by AdilIqbal95** [drachels/moodle-mod_hotquestion#54]
Hi, below are detailed some behat test failures across a number of different feature files.

**No.1 - /var/www/html/mod/hotquestion/tests/behat/add_hot_question_activity.feature:7**

--- Failed steps:

001 Scenario: Add a hotquestion activity and complete the activity as a student 
#/var/www/html/mod/hotquestion/tests/behat/add_hot_question_activity.feature:7
      And I navigate to "Logs" in current page administration   #/var/www/html/mod/hotquestion/tests/behat/add_hot_question_activity.feature:36
        Page administration menu not found. (Behat\Mink\Exception\ElementNotFoundException)
		
**No.2 - /var/www/html/mod/hotquestion/tests/behat/toolbar_export_to_csv_teacher.feature:32**

--- Failed steps:

001 Scenario: A teacher follows export to csv toolbutton to export questions 
#/var/www/html/mod/hotquestion/tests/behat/toolbar_export_to_csv_teacher.feature:32
      And I should see "Posted by Anonymous"                                 
#/var/www/html/mod/hotquestion/tests/behat/toolbar_export_to_csv_teacher.feature:123
        "Posted by Anonymous" text was not found in the page (Behat\Mink\Exception\ExpectationException)
	
**No.3 - /var/www/html/mod/hotquestion/tests/behat/toolbar_export_to_csv_admin.feature:32**
--- Failed steps:

001 Scenario: An admin follows export to csv toolbutton to export all site questions 
#/var/www/html/mod/hotquestion/tests/behat/toolbar_export_to_csv_admin.feature:32
      And I should see "Posted by Anonymous"                                         
#/var/www/html/mod/hotquestion/tests/behat/toolbar_export_to_csv_admin.feature:123
        "Posted by Anonymous" text was not found in the page (Behat\Mink\Exception\ExpectationException)

**No.4 - /var/www/html/mod/hotquestion/tests/behat/questions_vote.feature:28**

--- Failed steps:

001 Scenario: A user follows vote to increase heat # /var/www/html/mod/hotquestion/tests/behat/questions_vote.feature:28
      And I should see "Posted by Anonymous"       # /var/www/html/mod/hotquestion/tests/behat/questions_vote.feature:41
        "Posted by Anonymous" text was not found in the page (Behat\Mink\Exception\ExpectationException)

**No.5 - /var/www/html/mod/hotquestion/tests/behat/hotquestion_no_calendar_capabilities.feature:7**

--- Failed steps:

Scenario: Editing a HotQuestion with no calendar capabilites

And I add a "Hotquestion" to section "1" and I fill the form with:: Javascript is required for this step. Please use the 'the following "activity" exists:' data generator instead. (Behat\Mink\Exception\DriverException)

**Comment by drachels** [comment]
Behat tests are something I have been meaning to try and work on for the past four years. Four years ago, a server upgrade broke my behat capability. Unfortunately, right at that time we discovered my wife had pancreatic cancer. With all the doctor visits and chemotherapy treatments, my coding time was very limited. She has recently passed away, and it has only been the past two months in which I have had the time and the desire to try and get caught up with all the programming projects I have going on. If you can provide upgrade behat tests, I will be happy to include them in the next release, otherwise it still may be some time before I can get to them as I have two major projects in development for Hot Question as well as a few more for Diary and MooTyper.

**Comment by AdilIqbal95** [comment]
I'm very sorry to hear about this. I hope you are well. I don't have the capacity at the moment but will push a fix if I get the chance.

**Comment by drachels** [comment]
Thanks, for the reply. I totally understand if you can't do anything right now. I am swamped myself, and other things are coming up that I have to take care of such as my lawn mower has decided to quit...got to get if fixed as the grass is getting too tall for my poor little dog.

**Comment by lucaboesch** [comment]
#96 resolves this.
