### ISSUE TITLE
Anonymous posts no longer work.

### ISSUE THREAD

**Issue by miotto** [drachels/moodle-mod_hotquestion#55]
Anonymous posts no longer work since commit [190b060](https://github.com/drachels/moodle-mod_hotquestion/commit/190b060671e89c1bab45338e77927430a61fc6fa)
In file `view.php` in line 172 the parameter anonymous is set to NULL.
Replace the line
`if($fromform->anonymous = NULL) {`
with 
`if (isset($fromform->anonymous) && $fromform->anonymous) {`

Info: The element `$newentry` is actually never used.

**Comment by drachels** [comment]
That commit was over six months ago from a work in progress. You can see that from all the debugging entries for print_object in the code. The files in the current Hot Question v4.02 (Build: 2022041000) release on the Moodle download page, has that line of code in an entirely different location and anonymous posts do work as shown in the picture.
![AnonymousPostTest](https://user-images.githubusercontent.com/1018249/168427715-c365378a-8723-4953-b3d8-90f99a08052b.png)
.

**Comment by drachels** [comment]
Sorry to take so long to reply. Having problems with my riding lawn mower and had to load it up and take it to another town for repair. Then spent hours with a technician trying to figure out what is wrong with my house air conditioner. Seems that a big chunk of the inside unit will have to be replaced. The condenser drip pan has sprung a leak in two places and the condenser has developed a pin hole causing a slow freon leak. The thing is less than three years old and this should not be happening.

Anyway, thanks for your input. I hate to say this but that release was made while my wife was in the terminal phase of pancreatic cancer. When I look at the code, I can see that it has other problems that need to be addressed. I will see what I can do.

**Comment by drachels** [comment]
Just created branch, MOODLE_410_BETA_RC1, that includes the fix for anonymous posts and also adds grades and completion capabilities. It does still have a bunch of debugging code in it that I will remove after some more testing.

**Comment by drachels** [comment]
Due to all the health problems I have had lately, I forgot to close this as being fixed in current versions.
