### ISSUE TITLE
Let students view questions after "close time"

### ISSUE THREAD

**Issue by Kemmotar83** [drachels/moodle-mod_hotquestion#68]
Hi,

now, when the "close time" has passed, the activity is considered completely closed and students cannot view any of the questions submitted.
It could be interesting to let teachers decide if questions should be still available to students in "read-only mode" (without any action like submit, vote, ecc... available).

Maybe a single yes/no config in the Availability section could be enough.

Do you think this could be done easily? Could be useful a help to develop this feature?

Kind regards,
Giorgio

**Comment by drachels** [comment]
Thanks for your continued interest in improving the HotQuestion plugin. I am reasonably sure that this would be fairly easy to implement, but the only problem I see is finding the time to do it. I will add this to my TODO list of things for HotQuestion.

**Comment by Kemmotar83** [comment]
Hi Al,

since I'll need to add a field to "hotquestion" table and consequently bump the version (also for the upgrade.php), how can I proceed ?

Thanks,
Giorgio

**Comment by drachels** [comment]
I thought there might be an easy, quick way, to do this, but it did not work. Adding a new field to the mdl_hotquestion table involves other stuff that has to be done. Basically, it will require changes to multiple files, that I don't think I will be able to get to for a few days. I have played "hooky" for two days and really need to get back to my other project.

**Comment by Kemmotar83** [comment]
The only other way is to change the default behavior, without any configuration, but I'm not sure that this could be a good idea.
I'll think about other solutions, otherwise I'll wait when you'll be able to focus on this.

**Comment by drachels** [comment]
Sorry to take so long to get back to this. I finally made a new Diary v3.7.1 release yesterday, and I have already found bugs in it, today! Since most of what I found does not really affect how Diary works, I am going to work on this for a bit, before I do anything about Diary.

**Comment by Kemmotar83** [comment]
Hi Al,

do you think to work on this issue by yourself, or do you need some help? If necessary, I'll be happy to help.

My idea is "simple". With a specific flag in the module settings, anyone with "mod/hotquestion:manage" capability could set if questions, rates, ... will be still available after end time (obviously in read-only mode).
I know that this "simple" idea could not be that simple to be implemented, that why you could ask for any help.

Thanks again,
Giorgio

**Comment by drachels** [comment]
Hi Giorgio,
Sure, if you can come up with a "simple" fix, I will be happy to look at it and include it in the next release. I had to leave it out in the recent v4.1.3 as I am trying to get out early bird releases of all my plugins, and in one of them, I just discovered a pretty major bug that I have to fix. I will work on it last.

**Comment by drachels** [comment]
I have had to add some things, and modify some, plus I have just moved your three new availability functions to hotquestion/classes/local.hqavailable.php.

Most important additions was to back up, and I have made it so students cannot change their votes when the activity closes, as that would allow them to alter their grade. However, they can still add comments, as they are ungraded.

**Comment by Kemmotar83** [comment]
Hi @drachels , thank you again for your precious work!

**Comment by drachels** [comment]
Hi @Kemmotar83, 
Thanks so much for your contribution to this new capability. I will try to have a new, STABLE, release in another hour, or so. Got a few last minute checks. Note that right now I cannot verify your new behat test as my server for behat testing is dead, and needs to be rebuilt.
